window.COUNTRY_CURRENCY_DB = [
  { country: "United States", currency: "USD", symbol: "$", alternativeSymbols: ["US$", "USD"] },
  { country: "European Union", currency: "EUR", symbol: "€", alternativeSymbols: ["Euro", "EUR"] }, 
  { country: "United Kingdom", currency: "GBP", symbol: "£", alternativeSymbols: ["GBP"] },
  { country: "Turkey", currency: "TRY", symbol: "₺", alternativeSymbols: ["TL", "TRY", "TRL"] },
  { country: "Japan", currency: "JPY", symbol: "¥", alternativeSymbols: ["円", "JPY"] },
  { country: "China", currency: "CNY", symbol: "¥", alternativeSymbols: ["RMB", "元", "CN¥"] },
  { country: "Norway", currency: "NOK", symbol: "kr", alternativeSymbols: [] },
  { country: "Sweden", currency: "SEK", symbol: "kr", alternativeSymbols: [":-"] },
  { country: "Denmark", currency: "DKK", symbol: "kr", alternativeSymbols: ["Dkr"] },
  { country: "Switzerland", currency: "CHF", symbol: "Fr", alternativeSymbols: ["CHF"] },
  { country: "Australia", currency: "AUD", symbol: "$", alternativeSymbols: ["A$", "Au$"] },
  { country: "Canada", currency: "CAD", symbol: "$", alternativeSymbols: ["C$", "Can$", "CAD"] },
  { country: "New Zealand", currency: "NZD", symbol: "$", alternativeSymbols: ["NZ$", "$NZ"] },
  { country: "Russia", currency: "RUB", symbol: "₽", alternativeSymbols: ["руб", "RUB"] }, 

  { country: "Afghanistan", currency: "AFN", symbol: "؋", alternativeSymbols: ["Af", "Afs"] },
  { country: "Albania", currency: "ALL", symbol: "Lek", alternativeSymbols: ["Lek"] },
  { country: "Algeria", currency: "DZD", symbol: "د.ج", alternativeSymbols: ["DA"] },
  { country: "American Samoa", currency: "USD", symbol: "$", alternativeSymbols: ["US$", "USD"] },
  { country: "Andorra", currency: "EUR", symbol: "€", alternativeSymbols: ["Euro", "EUR"] },
  { country: "Angola", currency: "AOA", symbol: "Kz", alternativeSymbols: [] },
  { country: "Anguilla", currency: "XCD", symbol: "$", alternativeSymbols: ["EC$"] },
  { country: "Antarctica", currency: "—", symbol: "", alternativeSymbols: [] },
  { country: "Antigua and Barbuda", currency: "XCD", symbol: "$", alternativeSymbols: ["EC$"] },
  { country: "Argentina", currency: "ARS", symbol: "$", alternativeSymbols: ["Arg$"] },
  { country: "Armenia", currency: "AMD", symbol: "֏", alternativeSymbols: ["dram"] },
  { country: "Aruba", currency: "AWG", symbol: "ƒ", alternativeSymbols: ["Afl"] },
  { country: "Austria", currency: "EUR", symbol: "€", alternativeSymbols: ["Euro"] },
  { country: "Azerbaijan", currency: "AZN", symbol: "₼", alternativeSymbols: ["man", "manat"] },
  { country: "Bahamas", currency: "BSD", symbol: "$", alternativeSymbols: ["B$"] },
  { country: "Bahrain", currency: "BHD", symbol: ".د.ب", alternativeSymbols: ["BD"] },
  { country: "Bangladesh", currency: "BDT", symbol: "৳", alternativeSymbols: ["Tk"] },
  { country: "Barbados", currency: "BBD", symbol: "$", alternativeSymbols: ["Bds$"] },
  { country: "Belarus", currency: "BYN", symbol: "Br", alternativeSymbols: ["бел. руб"] },
  { country: "Belgium", currency: "EUR", symbol: "€", alternativeSymbols: ["Euro"] },
  { country: "Belize", currency: "BZD", symbol: "BZ$", alternativeSymbols: ["$"] },
  { country: "Benin", currency: "XOF", symbol: "CFA", alternativeSymbols: ["FCFA"] },
  { country: "Bermuda", currency: "BMD", symbol: "$", alternativeSymbols: ["BD$"] },
  { country: "Bhutan", currency: "BTN", symbol: "Nu.", alternativeSymbols: [] },
  { country: "Bolivia", currency: "BOB", symbol: "Bs.", alternativeSymbols: ["$b"] },
  { country: "Bosnia and Herzegovina", currency: "BAM", symbol: "KM", alternativeSymbols: [] },
  { country: "Botswana", currency: "BWP", symbol: "P", alternativeSymbols: [] },
  { country: "Bouvet Island", currency: "NOK", symbol: "kr", alternativeSymbols: [] },
  { country: "Brazil", currency: "BRL", symbol: "R$", alternativeSymbols: [] },
  { country: "British Indian Ocean Territory", currency: "USD", symbol: "$", alternativeSymbols: ["US$"] },
  { country: "Brunei Darussalam", currency: "BND", symbol: "$", alternativeSymbols: ["B$"] },
  { country: "Bulgaria", currency: "EUR", symbol: "€", alternativeSymbols: ["Euro", "lev", "BGN"] },
  { country: "Burkina Faso", currency: "XOF", symbol: "CFA", alternativeSymbols: ["FCFA"] },
  { country: "Burundi", currency: "BIF", symbol: "FBu", alternativeSymbols: [] },
  { country: "Cambodia", currency: "KHR", symbol: "៛", alternativeSymbols: [] },
  { country: "Cameroon", currency: "XAF", symbol: "FCFA", alternativeSymbols: ["XAF"] },
  { country: "Cape Verde", currency: "CVE", symbol: "Esc", alternativeSymbols: [] },
  { country: "Cayman Islands", currency: "KYD", symbol: "$", alternativeSymbols: ["CI$"] },
  { country: "Central African Republic", currency: "XAF", symbol: "FCFA", alternativeSymbols: [] },
  { country: "Chad", currency: "XAF", symbol: "FCFA", alternativeSymbols: [] },
  { country: "Chile", currency: "CLP", symbol: "$", alternativeSymbols: ["CLP$"] },
  { country: "Christmas Island", currency: "AUD", symbol: "$", alternativeSymbols: ["A$"] },
  { country: "Cocos (Keeling) Islands", currency: "AUD", symbol: "$", alternativeSymbols: ["A$"] },
  { country: "Colombia", currency: "COP", symbol: "$", alternativeSymbols: ["COL$", "COP"] },
  { country: "Comoros", currency: "KMF", symbol: "CF", alternativeSymbols: [] },
  { country: "Congo", currency: "XAF", symbol: "FCFA", alternativeSymbols: [] },
  { country: "Congo, The Democratic Republic of the", currency: "CDF", symbol: "FC", alternativeSymbols: [] },
  { country: "Cook Islands", currency: "NZD", symbol: "$", alternativeSymbols: ["NZ$"] },
  { country: "Costa Rica", currency: "CRC", symbol: "₡", alternativeSymbols: [] },
  { country: "Croatia", currency: "EUR", symbol: "€", alternativeSymbols: ["Euro"] },
  { country: "Cuba", currency: "CUP", symbol: "$", alternativeSymbols: ["$MN"] },
  { country: "Cyprus", currency: "EUR", symbol: "€", alternativeSymbols: [] },
  { country: "Czech Republic", currency: "CZK", symbol: "Kč", alternativeSymbols: [] },
  { country: "Djibouti", currency: "DJF", symbol: "Fdj", alternativeSymbols: [] },
  { country: "Dominica", currency: "XCD", symbol: "$", alternativeSymbols: ["EC$"] },
  { country: "Dominican Republic", currency: "DOP", symbol: "RD$", alternativeSymbols: ["DOP$"] },
  { country: "Ecuador", currency: "USD", symbol: "$", alternativeSymbols: ["US$"] },
  { country: "Egypt", currency: "EGP", symbol: "£", alternativeSymbols: ["E£", "L.E."] },
  { country: "El Salvador", currency: "USD", symbol: "$", alternativeSymbols: ["US$"] },
  { country: "Equatorial Guinea", currency: "XAF", symbol: "FCFA", alternativeSymbols: [] },
  { country: "Eritrea", currency: "ERN", symbol: "Nqk", alternativeSymbols: [] },
  { country: "Estonia", currency: "EUR", symbol: "€", alternativeSymbols: [] },
  { country: "Ethiopia", currency: "ETB", symbol: "Br", alternativeSymbols: [] },
  { country: "Falkland Islands (Malvinas)", currency: "FKP", symbol: "£", alternativeSymbols: ["FK£"] },
  { country: "Faroe Islands", currency: "DKK", symbol: "kr", alternativeSymbols: ["Dkr"] },
  { country: "Fiji", currency: "FJD", symbol: "$", alternativeSymbols: ["FJ$"] },
  { country: "Finland", currency: "EUR", symbol: "€", alternativeSymbols: [] },
  { country: "France", currency: "EUR", symbol: "€", alternativeSymbols: [] },
  { country: "French Guiana", currency: "EUR", symbol: "€", alternativeSymbols: [] },
  { country: "French Polynesia", currency: "XPF", symbol: "₣", alternativeSymbols: ["CFP"] },
  { country: "French Southern Territories", currency: "EUR", symbol: "€", alternativeSymbols: [] },
  { country: "Gabon", currency: "XAF", symbol: "FCFA", alternativeSymbols: [] },
  { country: "Gambia", currency: "GMD", symbol: "D", alternativeSymbols: [] },
  { country: "Georgia", currency: "GEL", symbol: "₾", alternativeSymbols: ["ari"] },
  { country: "Germany", currency: "EUR", symbol: "€", alternativeSymbols: [] },
  { country: "Ghana", currency: "GHS", symbol: "₵", alternativeSymbols: ["GH¢", "GH₵"] },
  { country: "Gibraltar", currency: "GIP", symbol: "£", alternativeSymbols: [] },
  { country: "Greece", currency: "EUR", symbol: "€", alternativeSymbols: [] },
  { country: "Greenland", currency: "DKK", symbol: "kr", alternativeSymbols: ["Dkr"] },
  { country: "Grenada", currency: "XCD", symbol: "$", alternativeSymbols: ["EC$"] },
  { country: "Guadeloupe", currency: "EUR", symbol: "€", alternativeSymbols: [] },
  { country: "Guam", currency: "USD", symbol: "$", alternativeSymbols: ["US$"] },
  { country: "Guatemala", currency: "GTQ", symbol: "Q", alternativeSymbols: [] },
  { country: "Guernsey", currency: "GBP", symbol: "£", alternativeSymbols: [] },
  { country: "Guinea", currency: "GNF", symbol: "FG", alternativeSymbols: ["Fr", "GFr"] },
  { country: "Guinea-Bissau", currency: "XOF", symbol: "CFA", alternativeSymbols: ["FCFA"] },
  { country: "Guyana", currency: "GYD", symbol: "$", alternativeSymbols: ["G$", "GY$"] },
  { country: "Haiti", currency: "HTG", symbol: "G", alternativeSymbols: [] },
  { country: "Heard Island and McDonald Islands", currency: "AUD", symbol: "$", alternativeSymbols: ["A$"] },
  { country: "Holy See (Vatican City State)", currency: "EUR", symbol: "€", alternativeSymbols: [] },
  { country: "Honduras", currency: "HNL", symbol: "L", alternativeSymbols: [] },
  { country: "Hong Kong", currency: "HKD", symbol: "$", alternativeSymbols: ["HK$", "元"] },
  { country: "Hungary", currency: "HUF", symbol: "Ft", alternativeSymbols: [] },
  { country: "Iceland", currency: "ISK", symbol: "kr", alternativeSymbols: ["Íkr"] },
  { country: "India", currency: "INR", symbol: "₹", alternativeSymbols: ["Rs", "INR"] },
  { country: "Indonesia", currency: "IDR", symbol: "Rp", alternativeSymbols: [] },
  { country: "Iran, Islamic Republic of", currency: "IRR", symbol: "﷼", alternativeSymbols: ["RI", "Toman"] },
  { country: "Iraq", currency: "IQD", symbol: "ع.د", alternativeSymbols: ["ID"] },
  { country: "Ireland", currency: "EUR", symbol: "€", alternativeSymbols: [] },
  { country: "Isle of Man", currency: "GBP", symbol: "£", alternativeSymbols: [] },
  { country: "Israel", currency: "ILS", symbol: "₪", alternativeSymbols: ["NIS"] },
  { country: "Italy", currency: "EUR", symbol: "€", alternativeSymbols: [] },
  { country: "Ivory Coast", currency: "XOF", symbol: "CFA", alternativeSymbols: ["FCFA"] },
  { country: "Jamaica", currency: "JMD", symbol: "J$", alternativeSymbols: ["$"] },
  { country: "Jersey", currency: "GBP", symbol: "£", alternativeSymbols: [] },
  { country: "Jordan", currency: "JOD", symbol: "د.ا", alternativeSymbols: ["JD"] },
  { country: "Kazakhstan", currency: "KZT", symbol: "₸", alternativeSymbols: [] },
  { country: "Kenya", currency: "KES", symbol: "KSh", alternativeSymbols: ["Sh"] },
  { country: "Kiribati", currency: "AUD", symbol: "$", alternativeSymbols: ["A$"] },
  { country: "Korea, Democratic People's Republic of", currency: "KPW", symbol: "₩", alternativeSymbols: [] },
  { country: "Korea, Republic of", currency: "KRW", symbol: "₩", alternativeSymbols: ["KRW"] },
  { country: "Kuwait", currency: "KWD", symbol: "د.ك", alternativeSymbols: ["KD"] },
  { country: "Kyrgyzstan", currency: "KGS", symbol: "с", alternativeSymbols: ["som"] },
  { country: "Lao People's Democratic Republic", currency: "LAK", symbol: "₭", alternativeSymbols: ["₭N"] },
  { country: "Latvia", currency: "EUR", symbol: "€", alternativeSymbols: [] },
  { country: "Lebanon", currency: "LBP", symbol: "ل.ل", alternativeSymbols: ["L£"] },
  { country: "Lesotho", currency: "LSL", symbol: "L", alternativeSymbols: ["M"] },
  { country: "Liberia", currency: "LRD", symbol: "$", alternativeSymbols: ["L$", "LD$"] },
  { country: "Libyan Arab Jamahiriya", currency: "LYD", symbol: "ل.د", alternativeSymbols: ["LD"] },
  { country: "Liechtenstein", currency: "CHF", symbol: "Fr.", alternativeSymbols: ["CHF"] },
  { country: "Lithuania", currency: "EUR", symbol: "€", alternativeSymbols: [] },
  { country: "Luxembourg", currency: "EUR", symbol: "€", alternativeSymbols: [] },
  { country: "Macao", currency: "MOP", symbol: "P", alternativeSymbols: ["MOP$"] },
  { country: "Macedonia, The Former Yugoslav Republic of", currency: "MKD", symbol: "ден", alternativeSymbols: ["den"] },
  { country: "Madagascar", currency: "MGA", symbol: "Ar", alternativeSymbols: [] },
  { country: "Malawi", currency: "MWK", symbol: "MK", alternativeSymbols: [] },
  { country: "Malaysia", currency: "MYR", symbol: "RM", alternativeSymbols: [] },
  { country: "Maldives", currency: "MVR", symbol: "Rf", alternativeSymbols: ["MRF"] },
  { country: "Mali", currency: "XOF", symbol: "CFA", alternativeSymbols: ["FCFA"] },
  { country: "Malta", currency: "EUR", symbol: "€", alternativeSymbols: [] },
  { country: "Marshall Islands", currency: "USD", symbol: "$", alternativeSymbols: ["US$"] },
  { country: "Martinique", currency: "EUR", symbol: "€", alternativeSymbols: [] },
  { country: "Mauritania", currency: "MRU", symbol: "UM", alternativeSymbols: [] },
  { country: "Mauritius", currency: "MUR", symbol: "₨", alternativeSymbols: [] },
  { country: "Mayotte", currency: "EUR", symbol: "€", alternativeSymbols: [] },
  { country: "Mexico", currency: "MXN", symbol: "$", alternativeSymbols: ["Mex$"] },
  { country: "Micronesia, Federated States of", currency: "USD", symbol: "$", alternativeSymbols: ["US$"] },
  { country: "Moldova, Republic of", currency: "MDL", symbol: "L", alternativeSymbols: ["lei"] },
  { country: "Monaco", currency: "EUR", symbol: "€", alternativeSymbols: [] },
  { country: "Mongolia", currency: "MNT", symbol: "₮", alternativeSymbols: [] },
  { country: "Montenegro", currency: "EUR", symbol: "€", alternativeSymbols: [] },
  { country: "Montserrat", currency: "XCD", symbol: "$", alternativeSymbols: ["EC$"] },
  { country: "Morocco", currency: "MAD", symbol: "د.م.", alternativeSymbols: ["DH"] },
  { country: "Mozambique", currency: "MZN", symbol: "MT", alternativeSymbols: [] },
  { country: "Myanmar", currency: "MMK", symbol: "Ks", alternativeSymbols: ["K"] },
  { country: "Namibia", currency: "NAD", symbol: "$", alternativeSymbols: ["N$"] },
  { country: "Nauru", currency: "AUD", symbol: "$", alternativeSymbols: ["A$"] },
  { country: "Nepal", currency: "NPR", symbol: "₨", alternativeSymbols: [] },
  { country: "Netherlands", currency: "EUR", symbol: "€", alternativeSymbols: [] },
  { country: "Netherlands Antilles", currency: "ANG", symbol: "ƒ", alternativeSymbols: ["NAƒ", "NAf"] },
  { country: "New Caledonia", currency: "XPF", symbol: "₣", alternativeSymbols: ["CFP"] },
  { country: "Nicaragua", currency: "NIO", symbol: "C$", alternativeSymbols: [] },
  { country: "Niger", currency: "XOF", symbol: "CFA", alternativeSymbols: ["FCFA"] },
  { country: "Nigeria", currency: "NGN", symbol: "₦", alternativeSymbols: [] },
  { country: "Niue", currency: "NZD", symbol: "$", alternativeSymbols: ["NZ$"] },
  { country: "Norfolk Island", currency: "AUD", symbol: "$", alternativeSymbols: ["A$"] },
  { country: "Northern Mariana Islands", currency: "USD", symbol: "$", alternativeSymbols: ["US$"] },
  { country: "Oman", currency: "OMR", symbol: "ر.ع.", alternativeSymbols: ["R.O."] },
  { country: "Pakistan", currency: "PKR", symbol: "₨", alternativeSymbols: [] },
  { country: "Palau", currency: "USD", symbol: "$", alternativeSymbols: ["US$"] },
  { country: "Palestinian Territory, Occupied", currency: "ILS", symbol: "₪", alternativeSymbols: [] },
  { country: "Panama", currency: "PAB", symbol: "B/.", alternativeSymbols: [] },
  { country: "Papua New Guinea", currency: "PGK", symbol: "K", alternativeSymbols: [] },
  { country: "Paraguay", currency: "PYG", symbol: "₲", alternativeSymbols: ["Gs"] },
  { country: "Peru", currency: "PEN", symbol: "S/.", alternativeSymbols: [] },
  { country: "Philippines", currency: "PHP", symbol: "₱", alternativeSymbols: ["P", "Php"] },
  { country: "Pitcairn", currency: "NZD", symbol: "$", alternativeSymbols: ["NZ$"] },
  { country: "Poland", currency: "PLN", symbol: "zł", alternativeSymbols: [] },
  { country: "Portugal", currency: "EUR", symbol: "€", alternativeSymbols: [] },
  { country: "Puerto Rico", currency: "USD", symbol: "$", alternativeSymbols: ["US$"] },
  { country: "Qatar", currency: "QAR", symbol: "ر.ق", alternativeSymbols: ["QR"] },
  { country: "Reunion", currency: "EUR", symbol: "€", alternativeSymbols: [] },
  { country: "Romania", currency: "RON", symbol: "lei", alternativeSymbols: [] },
  { country: "Russian Federation", currency: "RUB", symbol: "₽", alternativeSymbols: ["руб", "RUB"] },
  { country: "Rwanda", currency: "RWF", symbol: "FRw", alternativeSymbols: ["RF", "R₣"] },
  { country: "Saint Helena", currency: "SHP", symbol: "£", alternativeSymbols: [] },
  { country: "Saint Kitts and Nevis", currency: "XCD", symbol: "$", alternativeSymbols: ["EC$"] },
  { country: "Saint Lucia", currency: "XCD", symbol: "$", alternativeSymbols: ["EC$"] },
  { country: "Saint Pierre and Miquelon", currency: "EUR", symbol: "€", alternativeSymbols: [] },
  { country: "Saint Vincent and the Grenadines", currency: "XCD", symbol: "$", alternativeSymbols: ["EC$"] },
  { country: "Samoa", currency: "WST", symbol: "T", alternativeSymbols: ["WS$", "SAT", "ST"] },
  { country: "San Marino", currency: "EUR", symbol: "€", alternativeSymbols: [] },
  { country: "Sao Tome and Principe", currency: "STN", symbol: "Db", alternativeSymbols: [] },
  { country: "Saudi Arabia", currency: "SAR", symbol: "ر.س", alternativeSymbols: ["SAR", "SR"] },
  { country: "Senegal", currency: "XOF", symbol: "CFA", alternativeSymbols: ["FCFA"] },
  { country: "Serbia", currency: "RSD", symbol: "дин.", alternativeSymbols: ["din.", "RSD", "Din"] },
  { country: "Seychelles", currency: "SCR", symbol: "₨", alternativeSymbols: ["SRe", "SR"] },
  { country: "Sierra Leone", currency: "SLE", symbol: "Le", alternativeSymbols: [] },
  { country: "Singapore", currency: "SGD", symbol: "$", alternativeSymbols: ["S$"] },
  { country: "Slovakia", currency: "EUR", symbol: "€", alternativeSymbols: [] },
  { country: "Slovenia", currency: "EUR", symbol: "€", alternativeSymbols: [] },
  { country: "Solomon Islands", currency: "SBD", symbol: "$", alternativeSymbols: ["SI$"] },
  { country: "Somalia", currency: "SOS", symbol: "S", alternativeSymbols: ["Sh.So."] },
  { country: "South Africa", currency: "ZAR", symbol: "R", alternativeSymbols: [] },
  { country: "South Sudan", currency: "SSP", symbol: "£", alternativeSymbols: [] },
  { country: "Spain", currency: "EUR", symbol: "€", alternativeSymbols: [] },
  { country: "Sri Lanka", currency: "LKR", symbol: "₨", alternativeSymbols: ["SLRs", "LKR"] },
  { country: "Sudan", currency: "SDG", symbol: "ج.س.", alternativeSymbols: ["£Sd", "LS"] },
  { country: "Suriname", currency: "SRD", symbol: "$", alternativeSymbols: ["Sur$"] },
  { country: "Svalbard and Jan Mayen", currency: "NOK", symbol: "kr", alternativeSymbols: [] },
  { country: "Swaziland", currency: "SZL", symbol: "L", alternativeSymbols: ["E"] },
  { country: "Syrian Arab Republic", currency: "SYP", symbol: "£", alternativeSymbols: ["LS", "£S", "S£"] },
  { country: "Taiwan", currency: "TWD", symbol: "NT$", alternativeSymbols: ["NT"] },
  { country: "Tajikistan", currency: "TJS", symbol: "SM", alternativeSymbols: [] },
  { country: "Tanzania, United Republic of", currency: "TZS", symbol: "TSh", alternativeSymbols: [] },
  { country: "Thailand", currency: "THB", symbol: "฿", alternativeSymbols: [] },
  { country: "Timor-Leste", currency: "USD", symbol: "$", alternativeSymbols: ["US$"] },
  { country: "Togo", currency: "XOF", symbol: "CFA", alternativeSymbols: ["FCFA"] },
  { country: "Tokelau", currency: "NZD", symbol: "$", alternativeSymbols: ["NZ$"] },
  { country: "Tonga", currency: "TOP", symbol: "T$", alternativeSymbols: ["PT"] },
  { country: "Trinidad and Tobago", currency: "TTD", symbol: "TT$", alternativeSymbols: [] },
  { country: "Tunisia", currency: "TND", symbol: "د.ت", alternativeSymbols: ["DT"] },
  { country: "Turkmenistan", currency: "TMT", symbol: "m", alternativeSymbols: [] },
  { country: "Turks and Caicos Islands", currency: "USD", symbol: "$", alternativeSymbols: ["US$"] },
  { country: "Tuvalu", currency: "AUD", symbol: "$", alternativeSymbols: ["A$"] },
  { country: "Uganda", currency: "UGX", symbol: "USh", alternativeSymbols: [] },
  { country: "Ukraine", currency: "UAH", symbol: "₴", alternativeSymbols: ["грн"] },
  { country: "United Arab Emirates", currency: "AED", symbol: "د.إ", alternativeSymbols: ["Dhs", "DH", "AED"] },
  { country: "Uruguay", currency: "UYU", symbol: "$U", alternativeSymbols: [] },
  { country: "Uzbekistan", currency: "UZS", symbol: "лв", alternativeSymbols: ["so'm", "soʻm", "s'om", "сўм"] },
  { country: "Vanuatu", currency: "VUV", symbol: "VT", alternativeSymbols: [] },
  { country: "Venezuela", currency: "VES", symbol: "Bs.", alternativeSymbols: ["Bs.S"] },
  { country: "Vietnam", currency: "VND", symbol: "₫", alternativeSymbols: [] },
  { country: "Virgin Islands, British", currency: "USD", symbol: "$", alternativeSymbols: ["US$"] },
  { country: "Virgin Islands, U.S.", currency: "USD", symbol: "$", alternativeSymbols: ["US$"] },
  { country: "Wallis and Futuna", currency: "XPF", symbol: "₣", alternativeSymbols: ["CFP"] },
  { country: "Western Sahara", currency: "MAD", symbol: "د.م.", alternativeSymbols: ["DH"] },
  { country: "Yemen", currency: "YER", symbol: "﷼", alternativeSymbols: [] },
  { country: "Zambia", currency: "ZMW", symbol: "ZK", alternativeSymbols: [] },
  { country: "Zimbabwe", currency: "ZWD", symbol: "Z$", alternativeSymbols: [] }
];
